language: node_js
node_js:
- '6.11.2'
install:
- yarn install
script:
- yarn lint
- yarn build
- yarn test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master